---
version: '3.3'
services:
  postgres:
    image: postgres:15.4-alpine
    environment:
      - POSTGRES_PASSWORD=postgrespassword
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
